Filter out image_url for argo-rollouts

diff --git a/integration-tests/plugin-binaries.yaml b/integration-tests/plugin-binaries.yaml
--- a/integration-tests/plugin-binaries.yaml
+++ b/integration-tests/plugin-binaries.yaml
@@ -43,6 +43,15 @@ spec:
               # Install jq to extract values from SNAPSHOT
               dnf -y install jq
 
+              # Extract container image URL for Argo Rollouts from snapshot
+              IMAGE_URL=$(echo '$(params.SNAPSHOT)' | jq -r '.components[] | select(.name == "argo-rollouts") | .containerImage')
+              echo "IMAGE_URL: $IMAGE_URL"
+
+              if [ -z "$IMAGE_URL" ]; then
+                echo "ERROR: No Argo Rollouts image found in the snapshot."
+                exit 1
+              fi
+
               # Extract container image url from snapshot for testing
               IMAGE_URL=$(echo '$(params.SNAPSHOT)' | jq -r '.components[0].containerImage')
               echo "IMAGE_URL: $IMAGE_URL"
